<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="yadavrahulo4official" failures="1" tests="3" name="Default test" time="3.465" errors="0" timestamp="2023-06-18T14:05:20 IST">
  <testcase classname="org.learn.vtiger.testScripts.BaseTest" name="@BeforeSuite reportSetUp" time="0.028">
    <failure type="java.lang.Error" message="Unresolved compilation problem: 
">
      <![CDATA[java.lang.Error: Unresolved compilation problem: 

at org.learn.vtiger.utility.Utility.getUtility(Utility.java:78)
at org.learn.vtiger.testScripts.BaseTest.reportSetUp(BaseTest.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:317)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- @BeforeSuite reportSetUp -->
  <testcase classname="org.learn.vtiger.testScripts.BaseTest" name="@BeforeMethod launch_hitUrl_SetUp" time="-1.687077316989E9">
    <skipped/>
  </testcase> <!-- @BeforeMethod launch_hitUrl_SetUp -->
  <testcase classname="org.learn.vtiger.testScripts.BaseTest" name="@AfterMethod Logout" time="-1.687077317008E9">
    <skipped/>
  </testcase> <!-- @AfterMethod Logout -->
  <testcase classname="org.learn.vtiger.testScripts.BaseTest" name="@BeforeMethod launch_hitUrl_SetUp" time="-1.687077317015E9">
    <skipped/>
  </testcase> <!-- @BeforeMethod launch_hitUrl_SetUp -->
  <testcase classname="org.learn.vtiger.testScripts.BaseTest" name="@AfterMethod Logout" time="-1.687077317032E9">
    <skipped/>
  </testcase> <!-- @AfterMethod Logout -->
  <testcase classname="org.learn.vtiger.testScripts.TS01_Login" name="tc001_verifyLoginWithValidCredentials" time="0.0">
    <skipped/>
  </testcase> <!-- tc001_verifyLoginWithValidCredentials -->
  <testcase classname="org.learn.vtiger.testScripts.TS01_Login" name="tc002_verifyLoginWithInValidCredentials" time="0.0">
    <skipped/>
  </testcase> <!-- tc002_verifyLoginWithInValidCredentials -->
  <testcase classname="org.learn.vtiger.testScripts.TS01_Login" name="tc003LoginWithMultipleData" time="3.312">
    <failure type="org.testng.internal.reflect.MethodMatcherException" message="
[public void org.learn.vtiger.testScripts.TS01_Login.tc003LoginWithMultipleData()] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: tc003LoginWithMultipleData([])
Arguments: [(java.util.HashMap) {Sr No:=Sr No:, UserName=UserName, ErrorMsg=ErrorMsg, Password=Password, Scenario=Scenario}]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void org.learn.vtiger.testScripts.TS01_Login.tc003LoginWithMultipleData()] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: tc003LoginWithMultipleData([])
Arguments: [(java.util.HashMap) {Sr No:=Sr No:, UserName=UserName, ErrorMsg=ErrorMsg, Password=Password, Scenario=Scenario}]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:43)
at org.testng.internal.Parameters.injectParameters(Parameters.java:914)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:34)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- tc003LoginWithMultipleData -->
</testsuite> <!-- Default test -->
